### ISSUE TITLE
Ensure compatiblity with Graal

### ISSUE THREAD

**Issue by mavilein** [lemonlabsuk/scala-uri#22]
Hey there,

first of all i would like to thank for developing this software! I am a backend engineer at [Prisma](https://github.com/prismagraphql/prisma). I am opening this issue as we are a happy user of this library and would like it to be compatible with Graal.

**What is Graal?**

Graal is a collection of tools. For one it is a JVM replacement that does not only run Java Bytecode but also other languages like Javascript or Ruby. It also comes with a tool called native image. This allows to **compile a JAR into a standalone binary**.

We would like to turn our Prisma Server into a lightweight binary with Graal.

However the Graal native image tool comes with some limitations. Some features of the JVM are not supported, e.g. the support for reflection is limited because it is not a good fit with ahead of time compilation. Therefore we created a [test suite](https://github.com/prismagraphql/graal-compatibility) to check the compatibility of our used dependencies with Graal. For each dependency we tried to come up with a super small program and see whether it compiles with Graal or not.

The program to test compatibility with this library can be found [here](https://github.com/prismagraphql/graal-compatibility/blob/master/jwt/src/main/scala/Main.scala).

**What's the problem we have hit?**
When running with `-H:+ReportUnsupportedElementsAtRuntime`:

```
Exception in thread "main" java.lang.NullPointerException
	at scala.io.Source$.fromURL(Source.scala:141)
	at scala.io.Source$.fromURL(Source.scala:136)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl$.trie$lzycompute(PublicSuffixSupportImpl.scala:12)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl$.trie(PublicSuffixSupportImpl.scala:10)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl.publicSuffix(PublicSuffixSupportImpl.scala:28)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl.publicSuffix$(PublicSuffixSupportImpl.scala:27)
	at io.lemonlabs.uri.DomainName.publicSuffix(Host.scala:59)
	at io.lemonlabs.uri.DomainName.longestSubdomain(Host.scala:115)
	at io.lemonlabs.uri.DomainName.subdomain(Host.scala:72)
	at io.lemonlabs.uri.Authority.subdomain(Authority.scala:46)
	at io.lemonlabs.uri.UrlWithAuthority.subdomain(Uri.scala:692)
	at io.lemonlabs.uri.UrlWithAuthority.subdomain$(Uri.scala:691)
	at io.lemonlabs.uri.AbsoluteUrl.subdomain(Uri.scala:780)
	at Main$.main(Main.scala:9)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

When running without `-H:+ReportUnsupportedElementsAtRuntime`:

```
Exception in thread "main" java.lang.NullPointerException
	at scala.io.Source$.fromURL(Source.scala:141)
	at scala.io.Source$.fromURL(Source.scala:136)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl$.trie$lzycompute(PublicSuffixSupportImpl.scala:12)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl$.trie(PublicSuffixSupportImpl.scala:10)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl.publicSuffix(PublicSuffixSupportImpl.scala:28)
	at io.lemonlabs.uri.inet.PublicSuffixSupportImpl.publicSuffix$(PublicSuffixSupportImpl.scala:27)
	at io.lemonlabs.uri.DomainName.publicSuffix(Host.scala:59)
	at io.lemonlabs.uri.DomainName.longestSubdomain(Host.scala:115)
	at io.lemonlabs.uri.DomainName.subdomain(Host.scala:72)
	at io.lemonlabs.uri.Authority.subdomain(Authority.scala:46)
	at io.lemonlabs.uri.UrlWithAuthority.subdomain(Uri.scala:692)
	at io.lemonlabs.uri.UrlWithAuthority.subdomain$(Uri.scala:691)
	at io.lemonlabs.uri.AbsoluteUrl.subdomain(Uri.scala:780)
	at Main$.main(Main.scala:9)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
```

**Note**: The Graal compilation terminates on the first encountered error. Therefore there might be more problems that need to be addressed.

**How can incompatibilities with Graal be fixed?**

Here is a [blog post](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) by the Graal team that explains how the native image tool is working and how they were able to compile a server built on top of netty into a binary.

We ran this test with Graal `1.0.0-rc5`. We used `scala-uri` version `1.1.1`.

**Comment by theon** [comment]
Hi there,

I am away on holiday at the moment, but will take a proper look into this when I get back later this week.

At first glance it looks like [public_suffix_trie.json](https://github.com/lemonlabsuk/scala-uri/blob/master/jvm/src/main/resources/public_suffix_trie.json) is not available on the classpath.

**Comment by theon** [comment]
Sorry for the delay following up on this.

As mentioned above, scala-uri loads a json resource from the classpath. Graal requires this resource to be specified at compile time with the [`-H:IncludeResources`](https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md) option.

I added this option to your graal-compatibility project like so: https://github.com/theon/graal-compatibility/commit/2728c8785614299231301c03ddf4429128394a65

This works and I get the following output when running `./check-compatibility.sh`:

```
Building WITHOUT ReportUnsupportedElementsAtRuntime flag...

Build on Server(pid: 76903, port: 61953)
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/svm/builder/svm.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/jvmci/graal.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/jvmci/graal-management.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/boot/graal-sdk.jar:/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/svm/library-support.jar:/work/graal-compatibility/target/lib_managed/HikariCP-2.5.1.jar:/work/graal-compatibility/target/lib_managed/akka-actor_2.12-2.5.11.jar:/work/graal-compatibility/target/lib_managed/amqp-client-4.1.0.jar:/work/graal-compatibility/target/lib_managed/bcpkix-jdk15on-1.57.jar:/work/graal-compatibility/target/lib_managed/bcprov-jdk15on-1.57.jar:/work/graal-compatibility/target/lib_managed/bugsnag-3.0.2.jar:/work/graal-compatibility/target/lib_managed/caffeine-2.5.5.jar:/work/graal-compatibility/target/lib_managed/commons-lang-2.6.jar:/work/graal-compatibility/target/lib_managed/config-1.3.2.jar:/work/graal-compatibility/target/lib_managed/cuid-java-0.1.1.jar:/work/graal-compatibility/target/lib_managed/evo-inflector-1.2.jar:/work/graal-compatibility/target/lib_managed/finagle-base-http_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-core_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-http2_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-http_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-netty4-http_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-netty4_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/finagle-toggle_2.12-6.44.0.jar:/work/graal-compatibility/target/lib_managed/guava-19.0.jar:/work/graal-compatibility/target/lib_managed/jackson-annotations-2.8.9.jar:/work/graal-compatibility/target/lib_managed/jackson-core-2.8.9.jar:/work/graal-compatibility/target/lib_managed/jackson-databind-2.8.9.jar:/work/graal-compatibility/target/lib_managed/jackson-datatype-jdk8-2.8.9.jar:/work/graal-compatibility/target/lib_managed/jackson-datatype-jsr310-2.8.9.jar:/work/graal-compatibility/target/lib_managed/jackson-module-paranamer-2.8.4.jar:/work/graal-compatibility/target/lib_managed/jackson-module-scala_2.12-2.8.4.jar:/work/graal-compatibility/target/lib_managed/java-dogstatsd-client-2.3.jar:/work/graal-compatibility/target/lib_managed/javax.servlet-api-3.1.0.jar:/work/graal-compatibility/target/lib_managed/jetty-http-9.3.0.v20150612.jar:/work/graal-compatibility/target/lib_managed/jetty-io-9.3.0.v20150612.jar:/work/graal-compatibility/target/lib_managed/jetty-server-9.3.0.v20150612.jar:/work/graal-compatibility/target/lib_managed/jetty-util-9.3.0.v20150612.jar:/work/graal-compatibility/target/lib_managed/joda-convert-1.7.jar:/work/graal-compatibility/target/lib_managed/joda-time-2.9.9.jar:/work/graal-compatibility/target/lib_managed/jsr305-3.0.0.jar:/work/graal-compatibility/target/lib_managed/jwt-core-impl_2.12-0.14.1.jar:/work/graal-compatibility/target/lib_managed/jwt-core_2.12-0.14.1.jar:/work/graal-compatibility/target/lib_managed/librato-java-2.1.0.jar:/work/graal-compatibility/target/lib_managed/logback-classic-1.1.7.jar:/work/graal-compatibility/target/lib_managed/logback-core-1.1.7.jar:/work/graal-compatibility/target/lib_managed/logstash-logback-encoder-4.7.jar:/work/graal-compatibility/target/lib_managed/macro-compat_2.12-1.1.1.jar:/work/graal-compatibility/target/lib_managed/mariadb-java-client-2.1.2.jar:/work/graal-compatibility/target/lib_managed/mysql-connector-java-8.0.12.jar:/work/graal-compatibility/target/lib_managed/netty-3.10.1.Final.jar:/work/graal-compatibility/target/lib_managed/netty-buffer-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-codec-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-codec-http-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-codec-http2-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-codec-socks-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-common-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-handler-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-handler-proxy-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-resolver-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-transport-4.1.9.Final.jar:/work/graal-compatibility/target/lib_managed/netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar:/work/graal-compatibility/target/lib_managed/paranamer-2.8.jar:/work/graal-compatibility/target/lib_managed/parboiled_2.12-2.1.4.jar:/work/graal-compatibility/target/lib_managed/play-functional_2.12-2.6.8.jar:/work/graal-compatibility/target/lib_managed/play-json_2.12-2.6.8.jar:/work/graal-compatibility/target/lib_managed/postgresql-42.2.2.jar:/work/graal-compatibility/target/lib_managed/protobuf-java-2.6.0.jar:/work/graal-compatibility/target/lib_managed/reactive-streams-1.0.0.jar:/work/graal-compatibility/target/lib_managed/scala-java8-compat_2.12-0.8.0.jar:/work/graal-compatibility/target/lib_managed/scala-library-2.12.3.jar:/work/graal-compatibility/target/lib_managed/scala-logging_2.12-3.7.0.jar:/work/graal-compatibility/target/lib_managed/scala-parser-combinators_2.12-1.0.4.jar:/work/graal-compatibility/target/lib_managed/scala-reflect-2.12.3.jar:/work/graal-compatibility/target/lib_managed/scala-uri_2.12-1.1.1.jar:/work/graal-compatibility/target/lib_managed/scalactic_2.12-3.0.4.jar:/work/graal-compatibility/target/lib_managed/scalaj-http_2.12-2.3.0.jar:/work/graal-compatibility/target/lib_managed/shapeless_2.12-2.3.3.jar:/work/graal-compatibility/target/lib_managed/slf4j-api-1.7.25.jar:/work/graal-compatibility/target/lib_managed/slick-hikaricp_2.12-3.2.3.jar:/work/graal-compatibility/target/lib_managed/slick-joda-mapper_2.12-2.3.0.jar:/work/graal-compatibility/target/lib_managed/slick_2.12-3.2.3.jar:/work/graal-compatibility/target/lib_managed/snakeyaml-1.19.jar:/work/graal-compatibility/target/lib_managed/spray-json_2.12-1.3.3.jar:/work/graal-compatibility/target/lib_managed/util-app_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-cache_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-codec_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-collection_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-core_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-function_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-hashing_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-jvm_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-lint_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-logging_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-registry_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-security_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-stats_2.12-6.43.0.jar:/work/graal-compatibility/target/lib_managed/util-tunable_2.12-6.43.0.jar:/work/graal-compatibility/scalaUri/target/scala-2.12/scalauri_2.12-0.1.0-SNAPSHOT.jar
-H:Path=/work/graal-compatibility
-H:IncludeResources=public_suffix_trie\.json
-H:Class=Main
-H:CLibraryPath=/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/jre/lib/svm/clibraries/darwin-amd64
-H:Name=main
]
   classlist:  13,829.02 ms
       (cap):     752.32 ms
       setup:   1,060.33 ms
  (typeflow):   5,017.31 ms
   (objects):   2,417.68 ms
  (features):      38.46 ms
    analysis:   7,627.09 ms
    universe:     200.37 ms
     (parse):     628.86 ms
    (inline):   1,174.91 ms
   (compile):   4,203.90 ms
     compile:   6,277.75 ms
       image:     769.43 ms
       write:     818.42 ms
     [total]:  30,608.59 ms



Running...

scalaUri..
Some(www)



Done

########################################################################################################


Competed in 151 ✅
```

Let me know if you need any further assistance.

**Comment by dpetrick** [comment]
@theon This seems to break on GraalVM RC8, and I'm not entirely sure why. Im currently investigating, but if you have a hunch I'd be happy to hear it. The error is exactly the one above. Other libraries that require resource inclusions still work, only this one refuses to execute correctly.

**Comment by dpetrick** [comment]
Just after writing the above comment I found the issue: Apparently, RC8s `native-image`s  resource includes are not additive anymore, and having multiple defined causes the last one specified to win. Sorry for pinging you.
