### ISSUE TITLE
AbsoluteUrl cannot be cast to RelativeUrl

### ISSUE THREAD

**Issue by ov7a** [lemonlabsuk/scala-uri#23]
<Description of Issue>

Code Example:
```scala
val url = Url.parse("http://example.com/somePart/subPart?q=1&p=2")
println(url.toRelativeUrl)
```

Results in
```
Exception in thread "main" java.lang.ClassCastException: AbsoluteUrl cannot be cast to RelativeUrl
	at io.lemonlabs.uri.Url$class.toRelativeUrl(Uri.scala:496)
	at io.lemonlabs.uri.AbsoluteUrl.toRelativeUrl(Uri.scala:795)
	at Test$.delayedEndpoint$Test$1(Test.scala:5)
	at Test$delayedInit$body.apply(Test.scala:3)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Test$.main(Test.scala:3)
	at Test.main(Test.scala)
```

while I'm expecting to get `/somePart/subPart?q=1&p=2`

scala 2.11.8
scala-uri 1.1.5

**Comment by ov7a** [comment]
It's seems that this method is 100% useless. Why it even exists?
```
def toRelativeUrl: RelativeUrl = this match {
    case r: RelativeUrl => r
    case _ => throw new ClassCastException(getClass.getSimpleName + " cannot be cast to RelativeUrl")
}
```

**Comment by theon** [comment]
Sorry for the delay replying.

That method is currently just syntactic sugar for a cast (`url.asInstanceOf[RelativeUrl]`). There is a similar `toAbsoluteUrl` method with an example of how it can be used in this [test case](https://github.com/lemonlabsuk/scala-uri/blob/2dc30fbea4076e50f3d4129f062f03e81ebf6754/shared/src/test/scala/io/lemonlabs/uri/DslTests.scala#L139).

I think your suggestion of converting an `AbsoluteUrl` to a `RelativeUrl` instead of throwing the ClassCastException makes total sense and I am happy to add that functionality. The reverse would not be possible in `toAbsoluteUrl`, so I will just leave that one throwing the Exception.

**Comment by theon** [comment]
I think we are on the same page. The API will only support `toSomething` converting methods. That said, these converting methods will still cast in the same way they do now for the cases already implemented. I will just add more cases to do conversions.

Your original example:

```scala
val url = Url.parse("http://example.com/somePart/subPart?q=1&p=2")
val converted = url.toRelativeUrl // Converted is a new instance of RelativeUrl with the value /somePart/subPart?q=1&p=2
```

Existing usage that will remain unchanged:

```scala
val url = Url.parse("/somePart/subPart?q=1&p=2")
val converted = url.toRelativeUrl // converted is the same instance as url, just cast from type Url to type RelativeUrl```

**Comment by ov7a** [comment]
Looks ok for me in regards to `toRelativeUrl` and exception class. 
It might be prudent to add information about this to the docs.
Continuing discussion, what is recommended way to convert RelativeUrl + host + scheme to AbsoluteUrl? (Recommended ways to conversions like this should also be documented, I think).

**Comment by theon** [comment]
Good shout. I have added both of these to the docs now.

 - https://github.com/lemonlabsuk/scala-uri#convert-an-absolute-url-to-a-relative-url
 - https://github.com/lemonlabsuk/scala-uri#convert-a-relative-url-to-an-absolute-url

**Comment by ov7a** [comment]
Thanks! That was cool.
